spring.application.name=MediConnect
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/medi_connect_db
spring.datasource.username=root
spring.datasource.password=abcd
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
